## Hello Tensorflow

In [28]:
import tensorflow as tf

hello = tf.constant("Hello TensorFlow!")
print(hello.numpy().decode('utf-8'))

Hello TensorFlow!


## Addition

In [1]:
import tensorflow as tf

x = 2
y = 3
z = tf.add(x, y, name='Add')

print(z.numpy())

5


## Direct dependency

In [8]:
import tensorflow as tf

a = tf.multiply(8,5)
b = tf.multiply(a,1)

print("a =", a.numpy())
print("b =", b.numpy())

a = 40
b = 40


## Indirect dependency

In [9]:
import tensorflow as tf

a = tf.multiply(8,5)
b = tf.multiply(4,3)

print("a =", a.numpy())
print("b =", b.numpy())

a = 40
b = 12


## Tensorflow graph

In [26]:
import tensorflow as tf

graph = tf.Graph()
with graph.as_default():
  z = tf.add(x, y, name='Add')
  print(z)

Tensor("Add:0", shape=(), dtype=int32)


## Sessions
Note: session are removed in v2

In [41]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

a = tf.multiply(3, 3)

with tf.compat.v1.Session() as sess:
    result = sess.run(a)
    print(result)

9


## Variables

In [33]:
import tensorflow as tf

x = tf.Variable(1212)
print(x.numpy())

1212


In [8]:
import tensorflow as tf

W3 = tf.Variable(tf.random.normal(shape=[500, 111]), name='weights')
print(W3.numpy())

[[ 0.21860667 -0.50987357 -1.0720963  ...  0.6952195   0.8731808
  -1.444568  ]
 [ 1.1236558  -0.38645372  0.13219169 ... -1.3076514   0.38034934
   1.6755697 ]
 [ 0.5010293   0.18303373 -0.2684355  ...  0.02703954 -1.678774
   0.07673653]
 ...
 [-0.34183478 -1.492573    1.0941448  ... -0.8783673   1.117596
  -1.1692251 ]
 [ 0.16346548 -0.20358084  0.324073   ...  0.20308279 -1.0646677
  -0.17654154]
 [-0.03119222 -0.55229217 -1.1741476  ... -0.9431647   0.5882801
  -0.38995823]]


In [9]:
import tensorflow as tf

# Create a variable within a scope
with tf.name_scope("scope"):
    a = tf.Variable(tf.zeros([2]), name="x")
    print(a.numpy())
    
with tf.name_scope("scope"):
    b = a  # Reuse the existing variable
    print(b.numpy())

[0. 0.]
[0. 0.]


## Constants

In [40]:
import tensorflow as tf

x = tf.constant(13)
print(x.numpy())

13


## Placeholder
Note: placeholders are removed in v2

In [10]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

# Define a placeholder
x = tf.compat.v1.placeholder("float", None)

# Define an operation
y = x + 3

# Create a session and run the operation
with tf.compat.v1.Session() as sess:
    result = sess.run(y, feed_dict={x: 0})  # You need to provide a value for the placeholder
    print(result)

2024-09-23 13:57:10.177025: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled


3.0


In [44]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
with tf.compat.v1.Session() as sess:
    result = sess.run(y, feed_dict={x: 5})
    print(result)

8.0


In [45]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
with tf.compat.v1.Session() as sess:
    result = sess.run(y, feed_dict={x: [3, 6, 9]})
    print(result)

[ 6.  9. 12.]


In [11]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
x = tf.compat.v1.placeholder("float", [None, 2])
y = x + 3
with tf.compat.v1.Session() as sess:
    x_val = [
        [
            1,
            2,
        ],
        [3, 4],
        [5, 6],
        [7, 8],
    ]
    result = sess.run(y, feed_dict={x: x_val})
    print(result)

[[ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]


## Tensor Board

In [4]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

x = tf.constant(1,name='x')
y = tf.constant(1,name='y')
a = tf.constant(3,name='a')
b = tf.constant(3,name='b')

prod1 = tf.multiply(x,y,name='prod1')
prod2 = tf.multiply(a,b,name='prod2')

sum = tf.add(prod1,prod2,name='sum')

with tf.compat.v1.Session() as sess:
  writer = tf.compat.v1.summary.FileWriter(logdir='./graphs',graph=sess.graph)
  print(sess.run(sum))


10


## Name scope

In [4]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()  # Disable eager execution for TensorFlow 1.x compatibility

# Define placeholders or constants
x = tf.compat.v1.placeholder(tf.float32, name="x")
y = tf.compat.v1.placeholder(tf.float32, name="y")
a = tf.compat.v1.placeholder(tf.float32, name="a")
b = tf.compat.v1.placeholder(tf.float32, name="b")

# Define operations using name scopes for graph visualization
with tf.compat.v1.name_scope("Product"):
    with tf.compat.v1.name_scope("prod1"):
        prod1 = tf.multiply(x, y, name="prod1")
    with tf.compat.v1.name_scope("prod2"):
        prod2 = tf.multiply(a, b, name="prod2")

with tf.compat.v1.name_scope("Sum"):
    sum_op = tf.add(prod1, prod2, name="sum")

# Run the session
with tf.compat.v1.Session() as sess:
    writer = tf.compat.v1.summary.FileWriter("./graphs", sess.graph)  # Save the graph for TensorBoard
    result = sess.run(sum_op, feed_dict={x: 2.0, y: 3.0, a: 4.0, b: 5.0})  # Provide values for placeholders
    print("Result:", result)
    
# Close the writer
writer.close()

Result: 26.0


## Handwritten digit classification

In [13]:
import tensorflow as tf
import tensorflow_datasets as tfds

# Disable eager execution for TensorFlow 1.x style
tf.compat.v1.disable_eager_execution()

# Load and preprocess the MNIST dataset
mnist_data, mnist_info = tfds.load('mnist', split='train', as_supervised=True, with_info=True)

# Normalize the images
def normalize_img(image, label):
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

# Prepare the dataset for training: batch and shuffle
batch_size = 128
mnist_data = mnist_data.map(normalize_img)
mnist_data = mnist_data.cache() \
                       .shuffle(buffer_size=10000) \
                       .batch(batch_size) \
                       .repeat()  # Repeat the dataset for multiple epochs

# Create an iterator for the dataset in TensorFlow 1.x style
iterator = tf.compat.v1.data.make_one_shot_iterator(mnist_data)
next_batch = iterator.get_next()

# Define placeholders for input and output
X = tf.compat.v1.placeholder(tf.float32, [None, 28, 28, 1], name="input")  # Modified shape to include channel
Y = tf.compat.v1.placeholder(tf.int64, [None], name="labels")

# Flatten the input using Keras Flatten layer
X_flattened = tf.keras.layers.Flatten()(X)

# Build the model using `tf.keras.layers.Dense`
with tf.compat.v1.name_scope("Model"):
    layer_1 = tf.keras.layers.Dense(512, activation='relu')(X_flattened)
    layer_2 = tf.keras.layers.Dense(256, activation='relu')(layer_1)
    layer_3 = tf.keras.layers.Dense(128, activation='relu')(layer_2)
    logits = tf.keras.layers.Dense(10)(layer_3)  # No activation for logits

# Define loss and optimizer
with tf.compat.v1.name_scope("Loss"):
    loss = tf.compat.v1.losses.sparse_softmax_cross_entropy(labels=Y, logits=logits)

with tf.compat.v1.name_scope("Optimizer"):
    optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=1e-4).minimize(loss)

# Define accuracy metric
with tf.compat.v1.name_scope("Accuracy"):
    correct_pred = tf.equal(tf.argmax(logits, 1), Y)
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

# Initialize all variables
init = tf.compat.v1.global_variables_initializer()

# Training parameters
num_epochs = 10
num_steps_per_epoch = mnist_info.splits['train'].num_examples // batch_size

# Start a session
with tf.compat.v1.Session() as sess:
    sess.run(init)

    for epoch in range(num_epochs):
        total_accuracy = 0
        total_loss = 0

        for step in range(num_steps_per_epoch):
            batch = sess.run(next_batch)
            batch_x, batch_y = batch[0], batch[1]
            
            # Reshape batch_x to have 4D shape (batch_size, 28, 28, 1)
            batch_x = batch_x.reshape(-1, 28, 28, 1)
            
            _, acc, l = sess.run([optimizer, accuracy, loss], feed_dict={X: batch_x, Y: batch_y})
            
            total_accuracy += acc
            total_loss += l

        print(f'Epoch {epoch+1}, Loss: {total_loss/num_steps_per_epoch:.4f}, Accuracy: {total_accuracy/num_steps_per_epoch:.4f}')


Epoch 1, Loss: 0.5383, Accuracy: 0.8656
Epoch 2, Loss: 0.1950, Accuracy: 0.9441
Epoch 3, Loss: 0.1433, Accuracy: 0.9591
Epoch 4, Loss: 0.1129, Accuracy: 0.9675
Epoch 5, Loss: 0.0919, Accuracy: 0.9736
Epoch 6, Loss: 0.0769, Accuracy: 0.9781
Epoch 7, Loss: 0.0645, Accuracy: 0.9815
Epoch 8, Loss: 0.0553, Accuracy: 0.9847
Epoch 9, Loss: 0.0477, Accuracy: 0.9864
Epoch 10, Loss: 0.0408, Accuracy: 0.9886


## Math operations in tensorflow
### Addition

In [1]:
import tensorflow as tf

x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

sum_result = tf.add(x, y)

print(sum_result.numpy())

[4. 4. 4.]


### Substraction

In [2]:
import tensorflow as tf

x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

difference = tf.subtract(x,y)
print(difference.numpy())

[-2.  0.  2.]


### Multiplication

In [3]:
import tensorflow as tf

x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

product = tf.multiply(x,y)
print(product.numpy())

[3. 4. 3.]


### Division

In [4]:
import tensorflow as tf

x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

division = tf.divide(x,y)
print(division.numpy())

[0.33333334 1.         3.        ]


### Dot Product

In [5]:
import tensorflow as tf

x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

dot_product = tf.reduce_sum(tf.multiply(x, y))
print(dot_product.numpy())

10.0


### Find min value

In [6]:
import tensorflow as tf

x = tf.constant([10, 0, 13, 9])
print(tf.argmin(x).numpy())

1


### Find max value

In [7]:
import tensorflow as tf

x = tf.constant([10, 0, 13, 9])
print(tf.argmax(x).numpy())

2


### Squared difference

In [8]:
import tensorflow as tf
x = tf.Variable([1,3,5,7,11])
y = tf.Variable([1])
print(tf.math.squared_difference(x,y).numpy())

[  0   4  16  36 100]


### Type casting

In [9]:
import tensorflow as tf
x = tf.Variable([1,3,5,7,11])
print(x.dtype)
x = tf.cast(x, dtype=tf.float32)
print(x.dtype)


<dtype: 'int32'>
<dtype: 'float32'>


### Concat 2 matrices (Row-wise)

In [10]:
import tensorflow as tf

x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]
print(tf.concat([x, y], 0).numpy())

[[3 6 9]
 [7 7 7]
 [4 5 6]
 [5 5 5]]


### Concat 2 matrices (Column-wise)

In [11]:
import tensorflow as tf

x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]
print(tf.concat([x, y], 1).numpy())

[[3 6 9 4 5 6]
 [7 7 7 5 5 5]]


### Stack 2 matrices

In [12]:
import tensorflow as tf

x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]
print(tf.stack(x, axis=1).numpy())

[[3 7]
 [6 7]
 [9 7]]


### Reduce mean

In [17]:
import tensorflow as tf
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
print("x =", x.numpy())
print("mean =", tf.reduce_mean(input_tensor=x).numpy())

x = [[1. 5.]
 [2. 3.]]
mean = 2.75


### Mean across row

In [18]:
import tensorflow as tf
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
print(tf.reduce_mean(input_tensor=x, axis=0).numpy())

[1.5 4. ]


### Mean across column

In [19]:
import tensorflow as tf
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
print(tf.reduce_mean(input_tensor=x, axis=1, keepdims=True).numpy())

[[3. ]
 [2.5]]


### Draw random values from the probability distributions

In [20]:
import tensorflow as tf
print(tf.random.normal(shape=(3, 2), mean=10.0, stddev=2.0).numpy())
print(
    tf.random.uniform(
        shape=(3, 2),
        minval=0,
        maxval=None,
        dtype=tf.float32,
    ).numpy()
)

[[10.626091  10.223464 ]
 [11.294839  12.112932 ]
 [10.209468   6.9676256]]
[[0.34333122 0.60177064]
 [0.7247     0.9661567 ]
 [0.597991   0.19115102]]


### Softmax probabilities

In [21]:
import tensorflow as tf
x = tf.constant([7., 2., 5.])
print(tf.nn.softmax(x).numpy())

[0.8756006  0.00589975 0.11849965]


### Gradients

In [22]:
import tensorflow as tf
def square(x):
  return tf.multiply(x, x)
with tf.GradientTape(persistent=True) as tape:
  print(square(6.).numpy())

36.0


## Defining a sequential model

In [32]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

# Convert lists to NumPy arrays
data_test = np.array([[1, 2, 3, 4, 5, 6, 7], [2, 3, 4, 5, 6, 7, 8], [3, 4, 5, 6, 7, 8, 9]])
labels_test = np.array([0, 1, 0])
data = np.array([
    [1, 2, 3, 4, 5, 6, 7],
    [2, 3, 4, 5, 6, 7, 8],
    [3, 4, 5, 6, 7, 8, 9],
    [4, 5, 6, 7, 8, 9, 10],
])
labels = np.array([0, 1, 0, 1])

# Define the model
model = Sequential()
model.add(Dense(13, input_dim=7, activation="relu"))
model.add(Dense(7, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

# Compile the model
model.compile(loss="binary_crossentropy", optimizer="sgd", metrics=["accuracy"])

model.fit(x=data, y=labels, epochs=100, batch_size=10)

# Evaluate the model
model.evaluate(x=data_test, y=labels_test)
model.evaluate(x=data, y=labels)

d:\Python\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 1.4456
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.5000 - loss: 1.0040
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.7912
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.7058
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5000 - loss: 0.6744
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5000 - loss: 0.6647
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7500 - loss: 0.6620
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.7500 - loss: 0.6612
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.7500 - loss: 0.6609
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.7500 - loss: 0.6607
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7500 - loss: 0.6605
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.7500 - los

[0.6461378335952759, 0.75]

### Defining a functional model

In [33]:
from keras.models import Model
from keras.layers import Input, Dense
import numpy as np

# Convert lists to NumPy arrays
data_test = np.array([[1, 2, 3, 4, 5, 6, 7], [2, 3, 4, 5, 6, 7, 8], [3, 4, 5, 6, 7, 8, 9]])
labels_test = np.array([0, 1, 0])
data = np.array([
    [1, 2, 3, 4, 5, 6, 7],
    [2, 3, 4, 5, 6, 7, 8],
    [3, 4, 5, 6, 7, 8, 9],
    [4, 5, 6, 7, 8, 9, 10],
])
labels = np.array([0, 1, 0, 1])

# Fix the input shape to match the number of features (7 in this case)
input = Input(shape=(7,))
layer1 = Dense(10, activation='relu')(input)
layer2 = Dense(10, activation='relu')(layer1)
output = Dense(1, activation='sigmoid')(layer2)

# Create the model
model = Model(inputs=input, outputs=output)

# Compile the model
model.compile(loss="binary_crossentropy", optimizer="sgd", metrics=["accuracy"])

model.fit(x=data, y=labels, epochs=100, batch_size=10)

# Evaluate the model
model.evaluate(x=data_test, y=labels_test)
model.evaluate(x=data, y=labels)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 3.4953
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.5000 - loss: 2.0186
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.5000 - loss: 0.9650
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.5000 - loss: 0.6973
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.5000 - loss: 0.6848
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5000 - loss: 0.6802
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5000 - loss: 0.6784
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5000 - loss: 0.6777
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.5000 - loss: 0.6772
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5000 - loss: 0.6766
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5000 - loss: 0.6762
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss

[0.6427375078201294, 0.75]